### ISSUE TITLE
request: weather horizontal scrolling with three day forecast

### ISSUE THREAD

**Issue by mock** [jayarc/Adaptdark#2]
**Reporter info**

 ```
 * Distribution - fedora 26
 * Gtk+ 3.0 version - 3.22.18-1
 * Desktop environment - gnome 3.22
 ```

**Adapta version (if you knew)**
cannot tell the version, but i compiled on 22 aug 2017.

**Related Application and/or Shell theming (or name of widget)**
gnome-shell-extension-openweather.noarch  1-0.29.20170423git648d491.fc26

**Actual issue**
it's a great theme. my only hiccup is the openweather extension requires horizontal scrolling when using a three day forecast. i've swapped out my fonts to use the noto sans ui font to see if the resizing might be handled by that, but it still has a scrollbar. and it seems like just a few pixels. is it possible to get that widened?

**Steps to reproduce (if you knew)**
set the forecast number of days to 3 instead of 2.

**Expected behaviour**
sized for 3 days.

**Other Note (feature-request, question, etc...)**
this is just a request and not really a bug.

**Comment by jayarc** [comment]
Thanks for reporting this, will check out soon and get back to you :)

**Comment by mock** [comment]
i also noted that highlighted text is white on white, which makes it a little tough to read what has been highlighted...in case you forgot what you highlighted.

**Comment by jayarc** [comment]
Got it, thanks for the info. I have time coming up to look at this soon and it would help me to see a screenshot of what you're seeing if you could.

**Comment by mock** [comment]
actually, i found the argument `--with-selection_color` as an override option. i'm trying that instead replacing #f5f5f5 with #696969 to see if that works for me.

heh, documentation.

**Comment by mock** [comment]
yes! that worked for me. the `--with-selection_color` argument handled the highlighting problem for me.

**Comment by jayarc** [comment]
Great thanks for helping improve :)
